<a href="https://colab.research.google.com/github/rakshithasetty41/machine-learning/blob/main/confusion_matrix_binary_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
y = [1,0,1,0,0,1,0,1,1,1,0,0]
len(y)

12

In [ ]:
ycap = [1,0,1,0,1,0,0,1,1,0,1,0]
len(ycap)

12

In [ ]:
import numpy as np
cm=np.zeros((2,2))
cm

array([[0., 0.],
       [0., 0.]])

In [ ]:
for i,j in zip(y,ycap):
  cm[i,j]+=1
cm

array([[4., 2.],
       [2., 4.]])

In [ ]:
def confusionmatrix(y,ycap):
  cm=np.zeros((2,2))
  for i,j in zip(y,ycap):
    cm[i,j]+=1
  return cm


In [ ]:
cm=confusionmatrix(y,ycap)
cm

array([[4., 2.],
       [2., 4.]])

In [ ]:
TN=cm[0,0]
FP=cm[0,1]
FN=cm[1,0]
TP=cm[1,1]




In [ ]:
precision = TP/ cm[:, 1].sum()
precision

np.float64(0.6666666666666666)

In [ ]:
recall=TP /cm[1].sum()
recall

np.float64(0.6666666666666666)

In [ ]:
p=np.array([precision,recall])
f1_score=2/(1/p).sum()
f1_score

np.float64(0.6666666666666666)

In [ ]:

accuracy = (TP + TN) / cm.sum()
accuracy

np.float64(0.6666666666666666)

In [ ]:
def cmetrics(cm):
  TP = cm[1, 1]
  TN = cm[0, 0]
  FP = cm[0, 1]
  FN = cm[1, 0]
  p = round(float(TP/cm[:, 1].sum()), 2)
  r = round(float(TP/cm[1].sum()), 2)
  pr = np.array([p, r])
  f1 = round(float(2/(1/pr).sum()), 2)
  acc = float(round((TP+TN)/cm.sum() * 100, 2))
  return (p, r, f1, acc)

In [ ]:
metrics  = cmetrics(cm)
metrics

(0.67, 0.67, 0.67, 66.67)

In [ ]:
precision , recall, f1, accuracy = cmetrics(cm)
print(" precision ", precision)
print(" recall ", recall)
print("F1-score " , f1)
print(" accuracy ", accuracy)

 precision  0.67
 recall  0.67
F1-score  0.67
 accuracy  66.67


In [ ]:
from sklearn.metrics import  confusion_matrix,precision_score,recall_score,f1_score,accuracy_score
confusion_matrix(y,ycap)

array([[4, 2],
       [2, 4]])

In [ ]:
precision_score(y,ycap)

0.6666666666666666

In [ ]:
recall_score(y,ycap)

0.6666666666666666

In [ ]:
f1_score(y,ycap)

0.6666666666666666

In [ ]:
accuracy_score(y,ycap)

0.6666666666666666