<a href="https://colab.research.google.com/github/rakshithasetty41/machine-learning/blob/main/confusion_matrix__multiclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# confusion matrix for multi class.

In [ ]:
y = [0, 1,2,0,1,2,2,1,1,0,0,2,1,0]
len(y)

14

In [ ]:
ycap = [0,1,2,1,0,1,0,2,1,2,0,2,1,1]
len(ycap)

14

In [ ]:
import numpy as np

In [ ]:
cm=np.zeros((3,3))
cm

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
for i ,j in zip(y,ycap):
  cm[i,j]+=1
cm

array([[2., 2., 1.],
       [1., 3., 1.],
       [1., 1., 2.]])

In [ ]:
def confusion(y,ycap):
  n=len(set(y))
  cm=np.zeros((n,n))
  for i,j in zip(y,ycap):
    cm[i,j]+=1
  return cm

In [ ]:
confusion(y,ycap)

array([[2., 2., 1.],
       [1., 3., 1.],
       [1., 1., 2.]])

In [ ]:
yt = [0, 1, 2, 3, 1, 2, 3, 0, 0]
ycapt = [0, 1, 2, 3, 1, 1, 2, 3, 1]
confusion(yt, ycapt)

array([[1., 1., 0., 1.],
       [0., 2., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 1.]])

In [ ]:
P0=cm[0,0]/cm[:,0].sum()
P0

np.float64(0.5)

In [ ]:
R0=cm[0,0]/cm[0].sum()
R0

np.float64(0.4)

In [ ]:
P1=cm[1,1]/cm[:,1].sum()
R1=cm[1,1]/cm[1].sum()
P2=cm[2,2]/cm[:,2].sum()
R2=cm[2,2]/cm[2].sum()

In [ ]:
P=[P0,P1,P2]
R=[R0,R1,R2]
list(zip(P,R))

[(np.float64(0.5), np.float64(0.4)),
 (np.float64(0.5), np.float64(0.6)),
 (np.float64(0.5), np.float64(0.5))]

In [ ]:
def metrics(cm):
  p=[]
  r=[]
  f1=[]
  for i in range(cm.shape[0]):
    pr=cm[i,i]/cm[:,i].sum()
    re=cm[i,i]/cm[i].sum()
    f=2/(1/pr+1/re)
    p.append(pr)
    r.append(re)
    f1.append(f)
  return np.array((p,r,f1)).T


In [ ]:
metrics(cm)

array([[0.5       , 0.4       , 0.44444444],
       [0.5       , 0.6       , 0.54545455],
       [0.5       , 0.5       , 0.5       ]])

In [ ]:
acc=(cm[0,0]+cm[1,1]+cm[2,2])/cm.sum()
acc

np.float64(0.5)

In [ ]:
accuracy=cm.diagonal().sum()/cm.sum()
accuracy

np.float64(0.5)

In [ ]:
from sklearn.metrics import confusion_matrix,multilabel_confusion_matrix,precision_score,recall_score,f1_score,accuracy_score
confusion_matrix(y,ycap)

array([[2, 2, 1],
       [1, 3, 1],
       [1, 1, 2]])

In [ ]:
accuracy_score(y,ycap)

0.5

In [ ]:
precision_score(y,ycap,average=None)

array([0.5, 0.5, 0.5])

In [ ]:
recall_score(y,ycap,average=None)

array([0.4, 0.6, 0.5])

In [ ]:
f1_score(y,ycap,average=None)

array([0.44444444, 0.54545455, 0.5       ])