<a href="https://colab.research.google.com/github/rakshithasetty41/machine-learning/blob/main/knn_classification_and_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
#knn classification

In [70]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/diabetics scores.txt')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              20 non-null     int64  
 1   BMI              20 non-null     float64
 2   Blood Pressure   20 non-null     int64  
 3   Glucose Level    20 non-null     int64  
 4   Insulin Level    20 non-null     int64  
 5   Diabetic Status  20 non-null     object 
 6   diabetic_score   20 non-null     float64
dtypes: float64(2), int64(4), object(1)
memory usage: 1.2+ KB
None


In [71]:
df.describe()

Age       BMI  Blood Pressure  Glucose Level  Insulin Level  \
count  20.000000  20.00000       20.000000      20.000000      20.000000   
mean   46.000000  26.95500      123.350000     138.600000      84.700000   
std     8.819834   2.70019        8.001809      16.346253       7.441703   
min    32.000000  22.70000      110.000000     105.000000      70.000000   
25%    38.750000  24.80000      116.750000     127.000000      78.750000   
50%    46.000000  26.75000      123.000000     142.000000      86.000000   
75%    53.250000  29.27500      130.000000     150.000000      90.250000   
max    61.000000  31.50000      136.000000     162.000000      96.000000   

       diabetic_score  
count       20.000000  
mean        74.337500  
std          6.851832  
min         61.350000  
25%         68.487500  
50%         74.675000  
75%         79.787500  
max         84.950000

In [72]:
df.head()

Age   BMI  Blood Pressure  Glucose Level  Insulin Level Diabetic Status  \
0   45  25.3             120            140             85             Yes   
1   50  28.1             130            155             90             Yes   
2   38  23.5             115            110             75              No   
3   60  31.2             135            160             95             Yes   
4   55  29.8             128            150             92             Yes   

   diabetic_score  
0           73.15  
1           80.05  
2           64.25  
3           84.10  
4           79.70

In [73]:
df.columns = df.columns.str.strip()
X = df[['Age', 'BMI', 'Blood Pressure', 'Glucose Level', 'Insulin Level']]
X

Age   BMI  Blood Pressure  Glucose Level  Insulin Level
0    45  25.3             120            140             85
1    50  28.1             130            155             90
2    38  23.5             115            110             75
3    60  31.2             135            160             95
4    55  29.8             128            150             92
5    32  22.7             110            105             70
6    42  26.5             118            135             80
7    48  27.3             125            145             88
8    35  24.1             113            120             78
9    58  30.5             132            158             93
10   41  25.8             121            138             82
11   47  27.0             126            144             87
12   36  24.9             114            122             76
13   53  29.1             130            148             89
14   40  26.0             119            132             81
15   61  31.5             136            162             96
16   39  23.8             117            128             77
17   49  27.5             129            146             90
18   37  24.5             116            124             79
19   54  30.0             133            150             91

In [74]:
y = df['Diabetic Status'].map({'Yes':1, 'No':0})  # Encode Yes=1, No=0
y

0     1
1     1
2     0
3     1
4     1
5     0
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
16    0
17    1
18    0
19    1
Name: Diabetic Status, dtype: int64

In [75]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42, stratify=y)
#stratify = y --> keep both 1,0 s in train and test splits.

In [76]:
x_train.shape

(14, 5)

In [77]:
x_test.shape

(6, 5)

In [78]:
y_train.shape

(14,)

In [79]:
y_test.shape

(6,)

In [80]:
y_train

7     1
9     1
0     1
12    0
17    1
15    1
2     0
4     1
6     0
1     1
16    0
18    0
19    1
5     0
Name: Diabetic Status, dtype: int64

In [81]:
y_test

10    0
3     1
14    0
11    1
13    1
8     0
Name: Diabetic Status, dtype: int64

In [82]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [83]:
x_train_scaled

array([[ 0.23094011,  0.1640397 ,  0.24094661,  0.417203  ,  0.45689259],
       [ 1.38564065,  1.3305442 ,  1.11549356,  1.17651246,  1.09654221],
       [-0.11547005, -0.56502562, -0.38372978,  0.1251609 ,  0.07310281],
       [-1.15470054, -0.71083868, -1.13334145, -0.92619066, -1.0782665 ],
       [ 0.34641016,  0.23694623,  0.74068772,  0.47561142,  0.71275243],
       [ 1.73205081,  1.69507686,  1.61523467,  1.41014614,  1.48033198],
       [-0.92376043, -1.2211844 , -1.00840617, -1.62709171, -1.20619643],
       [ 1.03923048,  1.07537134,  0.61575244,  0.7092451 ,  0.96861228],
       [-0.46188022, -0.12758643, -0.63360034, -0.1668812 , -0.56654681],
       [ 0.46188022,  0.45566582,  0.865623  ,  1.0012872 ,  0.71275243],
       [-0.80829038, -1.11182461, -0.75853562, -0.57574014, -0.95033658],
       [-1.03923048, -0.85665175, -0.8834709 , -0.80937382, -0.69447673],
       [ 0.92376043,  1.14827787,  1.24042883,  0.7092451 ,  0.84068236],
       [-1.61658075, -1.51281053, -1.6

In [84]:
x_test_scaled

array([[-0.57735027, -0.38275929, -0.25879451,  0.00834406, -0.31068696],
       [ 1.61658075,  1.58571706,  1.49029939,  1.2933293 ,  1.35240205],
       [-0.69282032, -0.30985276, -0.50866506, -0.34210646, -0.43861688],
       [ 0.11547005,  0.0546799 ,  0.36588189,  0.35879458,  0.32896266],
       [ 0.80829038,  0.82019848,  0.865623  ,  0.59242826,  0.58482251],
       [-1.27017059, -1.00246481, -1.25827673, -1.0430075 , -0.82240665]])

In [85]:
from sklearn.neighbors import  KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=5)
k=knn.fit(x_train_scaled,y_train)
k

KNeighborsClassifier()

In [86]:
y_pr=knn.predict(x_test_scaled)
y_pr

array([0, 1, 0, 1, 1, 0])

In [87]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac=accuracy_score(y_test,y_pr)
ac

1.0

In [88]:
import numpy as np

# Example new patient data
new_data = np.array([[46, 27.2, 124, 142, 86]])

# Scale using the same scaler fitted earlier
new_data_scaled = scaler.transform(new_data)

# Predict
prediction = knn.predict(new_data_scaled)
print("Predicted Diabetic Status:", "Yes" if prediction[0] == 1 else "No")



Predicted Diabetic Status: Yes


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [98]:
#knn regression
import pandas as pd
import numpy as np
df=pd.read_csv('/content/diabetics scores.txt')
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              20 non-null     int64  
 1   BMI              20 non-null     float64
 2   Blood Pressure   20 non-null     int64  
 3   Glucose Level    20 non-null     int64  
 4   Insulin Level    20 non-null     int64  
 5   Diabetic Status  20 non-null     object 
 6   diabetic_score   20 non-null     float64
dtypes: float64(2), int64(4), object(1)
memory usage: 1.2+ KB


In [97]:
df.head()

Age   BMI  Blood Pressure  Glucose Level  Insulin Level Diabetic Status  \
0   45  25.3             120            140             85             Yes   
1   50  28.1             130            155             90             Yes   
2   38  23.5             115            110             75              No   
3   60  31.2             135            160             95             Yes   
4   55  29.8             128            150             92             Yes   

   diabetic_score  
0           73.15  
1           80.05  
2           64.25  
3           84.10  
4           79.70

In [96]:
df.describe()

Age       BMI  Blood Pressure  Glucose Level  Insulin Level  \
count  20.000000  20.00000       20.000000      20.000000      20.000000   
mean   46.000000  26.95500      123.350000     138.600000      84.700000   
std     8.819834   2.70019        8.001809      16.346253       7.441703   
min    32.000000  22.70000      110.000000     105.000000      70.000000   
25%    38.750000  24.80000      116.750000     127.000000      78.750000   
50%    46.000000  26.75000      123.000000     142.000000      86.000000   
75%    53.250000  29.27500      130.000000     150.000000      90.250000   
max    61.000000  31.50000      136.000000     162.000000      96.000000   

       diabetic_score  
count       20.000000  
mean        74.337500  
std          6.851832  
min         61.350000  
25%         68.487500  
50%         74.675000  
75%         79.787500  
max         84.950000

In [99]:
X = df[['Age', 'BMI', 'Blood Pressure', 'Glucose Level', 'Insulin Level']]
y = df['diabetic_score']


In [100]:
X

Age   BMI  Blood Pressure  Glucose Level  Insulin Level
0    45  25.3             120            140             85
1    50  28.1             130            155             90
2    38  23.5             115            110             75
3    60  31.2             135            160             95
4    55  29.8             128            150             92
5    32  22.7             110            105             70
6    42  26.5             118            135             80
7    48  27.3             125            145             88
8    35  24.1             113            120             78
9    58  30.5             132            158             93
10   41  25.8             121            138             82
11   47  27.0             126            144             87
12   36  24.9             114            122             76
13   53  29.1             130            148             89
14   40  26.0             119            132             81
15   61  31.5             136            162             96
16   39  23.8             117            128             77
17   49  27.5             129            146             90
18   37  24.5             116            124             79
19   54  30.0             133            150             91

In [102]:
y

0     73.15
1     80.05
2     64.25
3     84.10
4     79.70
5     61.35
6     71.85
7     76.45
8     66.45
9     82.55
10    72.90
11    76.20
12    67.25
13    79.05
14    71.30
15    84.95
16    68.60
17    77.75
18    68.15
19    80.70
Name: diabetic_score, dtype: float64

In [105]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [106]:
x_train

Age   BMI  Blood Pressure  Glucose Level  Insulin Level
11   47  27.0             126            144             87
3    60  31.2             135            160             95
18   37  24.5             116            124             79
16   39  23.8             117            128             77
13   53  29.1             130            148             89
2    38  23.5             115            110             75
9    58  30.5             132            158             93
19   54  30.0             133            150             91
4    55  29.8             128            150             92
12   36  24.9             114            122             76
7    48  27.3             125            145             88
10   41  25.8             121            138             82
14   40  26.0             119            132             81
6    42  26.5             118            135             80

In [107]:
x_test

Age   BMI  Blood Pressure  Glucose Level  Insulin Level
0    45  25.3             120            140             85
17   49  27.5             129            146             90
15   61  31.5             136            162             96
1    50  28.1             130            155             90
8    35  24.1             113            120             78
5    32  22.7             110            105             70

In [108]:
y_train

11    76.20
3     84.10
18    68.15
16    68.60
13    79.05
2     64.25
9     82.55
19    80.70
4     79.70
12    67.25
7     76.45
10    72.90
14    71.30
6     71.85
Name: diabetic_score, dtype: float64

In [109]:
y_test

0     73.15
17    77.75
15    84.95
1     80.05
8     66.45
5     61.35
Name: diabetic_score, dtype: float64

In [110]:
x_train.shape

(14, 5)

In [111]:
x_test.shape

(6, 5)

In [112]:
y_test.shape

(6,)

In [113]:
y_train.shape

(14,)

In [116]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [117]:
from sklearn.neighbors import KNeighborsRegressor

knn_reg = KNeighborsRegressor(n_neighbors=5)
knn_reg.fit(x_train_scaled, y_train)


KNeighborsRegressor()

In [118]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

y_pred = knn_reg.predict(x_test_scaled)

print("R Score:", r2_score(y_test, y_pred))


R Score: 0.8389595673448367


In [121]:
import numpy as np

new_data = np.array([[46, 27.2, 124, 142, 86]])  # Age, BMI, BP, Glucose, Insulin
new_data_scaled = scaler.transform(new_data)

predicted_score = knn_reg.predict(new_data_scaled)
print("Predicted Diabetic Score:", predicted_score[0])


Predicted Diabetic Score: 73.74


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
