<a href="https://colab.research.google.com/github/rakshithasetty41/machine-learning/blob/main/logistic_With_GDA_loss%2Ccross_entropy%2Cmulti_class_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/diabetics scores.txt')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              20 non-null     int64  
 1   BMI              20 non-null     float64
 2   Blood Pressure   20 non-null     int64  
 3   Glucose Level    20 non-null     int64  
 4   Insulin Level    20 non-null     int64  
 5   Diabetic Status  20 non-null     object 
 6   diabetic_score   20 non-null     float64
dtypes: float64(2), int64(4), object(1)
memory usage: 1.2+ KB


In [ ]:
inputsdf=df.iloc[:,:-2]
inputs=inputsdf.to_numpy()
inputs

array([[ 45. ,  25.3, 120. , 140. ,  85. ],
       [ 50. ,  28.1, 130. , 155. ,  90. ],
       [ 38. ,  23.5, 115. , 110. ,  75. ],
       [ 60. ,  31.2, 135. , 160. ,  95. ],
       [ 55. ,  29.8, 128. , 150. ,  92. ],
       [ 32. ,  22.7, 110. , 105. ,  70. ],
       [ 42. ,  26.5, 118. , 135. ,  80. ],
       [ 48. ,  27.3, 125. , 145. ,  88. ],
       [ 35. ,  24.1, 113. , 120. ,  78. ],
       [ 58. ,  30.5, 132. , 158. ,  93. ],
       [ 41. ,  25.8, 121. , 138. ,  82. ],
       [ 47. ,  27. , 126. , 144. ,  87. ],
       [ 36. ,  24.9, 114. , 122. ,  76. ],
       [ 53. ,  29.1, 130. , 148. ,  89. ],
       [ 40. ,  26. , 119. , 132. ,  81. ],
       [ 61. ,  31.5, 136. , 162. ,  96. ],
       [ 39. ,  23.8, 117. , 128. ,  77. ],
       [ 49. ,  27.5, 129. , 146. ,  90. ],
       [ 37. ,  24.5, 116. , 124. ,  79. ],
       [ 54. ,  30. , 133. , 150. ,  91. ]])

In [ ]:
originals=inputs.copy()

In [ ]:
def scale(x):
  return (x-x.mean())/x.std()

In [ ]:
def scalematrix(x):
  for i in range(x.shape[1]):
    x[:,i]=scale(x[:,i])
  return x

In [ ]:
scaled_inputs=scalematrix(inputs)
scaled_inputs

array([[-0.11632626, -0.62884247, -0.42953131,  0.08787149,  0.04136063],
       [ 0.46530506,  0.4350602 ,  0.8526517 ,  1.02935178,  0.73070439],
       [-0.93061011, -1.31277989, -1.07062281, -1.79508907, -1.33732691],
       [ 1.6285677 ,  1.61295243,  1.4937432 ,  1.34317854,  1.42004816],
       [ 1.04693638,  1.0810011 ,  0.5962151 ,  0.71552502,  1.0064419 ],
       [-1.6285677 , -1.61675208, -1.71171431, -2.10891584, -2.02667068],
       [-0.46530506, -0.17288418, -0.68596791, -0.22595527, -0.64798314],
       [ 0.23265253,  0.13108801,  0.2115602 ,  0.40169825,  0.45496689],
       [-1.27958891, -1.08480075, -1.32705941, -1.16743555, -0.92372065],
       [ 1.39591517,  1.34697676,  1.1090883 ,  1.21764783,  1.14431065],
       [-0.58163132, -0.43885985, -0.30131301, -0.03765921, -0.37224563],
       [ 0.11632626,  0.01709844,  0.3397785 ,  0.3389329 ,  0.31709813],
       [-1.16326264, -0.78082856, -1.19884111, -1.04190485, -1.19945816],
       [ 0.81428385,  0.81502543,  0.8

In [ ]:
def scaletest(x):
  stds=[]
  for i in range(x.shape[1]):
    stds.append(x[:,i].std())
  return stds

In [ ]:
scaletest(scaled_inputs)

[np.float64(1.0000000000000002),
 np.float64(1.0000000000000002),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0)]

In [ ]:
scaletest(originals)

[np.float64(8.596510920134982),
 np.float64(2.6318197126703033),
 np.float64(7.799198676787251),
 np.float64(15.932357013323546),
 np.float64(7.2532751223154355)]

In [ ]:
dstat=df['Diabetic Status']
dstat

0     Yes
1     Yes
2      No
3     Yes
4     Yes
5      No
6      No
7     Yes
8      No
9     Yes
10     No
11    Yes
12     No
13    Yes
14     No
15    Yes
16     No
17    Yes
18     No
19    Yes
Name: Diabetic Status, dtype: object

In [ ]:
dhot = np.where(dstat=='Yes', 1, 0)
dhot

array([1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [ ]:
#input matrix
ones=np.ones(inputs.shape[0])
ones.size

20

In [ ]:
X=np.c_[ones,scaled_inputs]
X.shape

(20, 6)

In [ ]:
X

array([[ 1.        , -0.11632626, -0.62884247, -0.42953131,  0.08787149,
         0.04136063],
       [ 1.        ,  0.46530506,  0.4350602 ,  0.8526517 ,  1.02935178,
         0.73070439],
       [ 1.        , -0.93061011, -1.31277989, -1.07062281, -1.79508907,
        -1.33732691],
       [ 1.        ,  1.6285677 ,  1.61295243,  1.4937432 ,  1.34317854,
         1.42004816],
       [ 1.        ,  1.04693638,  1.0810011 ,  0.5962151 ,  0.71552502,
         1.0064419 ],
       [ 1.        , -1.6285677 , -1.61675208, -1.71171431, -2.10891584,
        -2.02667068],
       [ 1.        , -0.46530506, -0.17288418, -0.68596791, -0.22595527,
        -0.64798314],
       [ 1.        ,  0.23265253,  0.13108801,  0.2115602 ,  0.40169825,
         0.45496689],
       [ 1.        , -1.27958891, -1.08480075, -1.32705941, -1.16743555,
        -0.92372065],
       [ 1.        ,  1.39591517,  1.34697676,  1.1090883 ,  1.21764783,
         1.14431065],
       [ 1.        , -0.58163132, -0.43885985, -0.

In [ ]:
Y=np.c_[dhot]
Y.shape

(20, 1)

In [ ]:
Y

array([[1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [ ]:
#random weights
np.random.seed(101)
W=np.random.random((X.shape[1],Y.shape[1]))*2-1
W.shape

(6, 1)

In [ ]:
W

array([[ 0.03279726],
       [ 0.14133517],
       [-0.94305155],
       [-0.65695669],
       [ 0.37055396],
       [ 0.66779373]])

In [ ]:
def prediction(x,w):
  return 1/(1+np.exp(-x.dot(w)))

In [ ]:
def mse(y, ycap):
    return ((y-ycap)**2).mean()

In [ ]:
def derivative(p):
  return p*(1-p)

In [ ]:
conv = 0.00000001
ploss = 0
flag =0
for i in range(100000):
   ycap = prediction(X, W)
   e = Y - ycap
   closs = mse(Y, ycap)
   if i%1000==0:
      print(f"current loss after {i+1} iterations {closs}")
   delta = derivative(ycap)
   W += X.T.dot(delta) * 0.002
   if np.abs(ploss-closs) < conv:
     print(f"Training completed after {i+1} iterations ")
     flag = 1
     break
   ploss = closs
if flag==0:
   print("Training not completed , run few more iterations ")


current loss after 1 iterations 0.33397923935978474
current loss after 1001 iterations 0.4229541724575986
current loss after 2001 iterations 0.43715385162047893
current loss after 3001 iterations 0.44163347252554574
current loss after 4001 iterations 0.44380877562296417
current loss after 5001 iterations 0.4450904245185958
current loss after 6001 iterations 0.44593421208016587
current loss after 7001 iterations 0.4465313839273189
current loss after 8001 iterations 0.446976092546955
current loss after 9001 iterations 0.44732002532593845
current loss after 10001 iterations 0.44759390163084234
current loss after 11001 iterations 0.4478171188045971
current loss after 12001 iterations 0.4480025246679464
current loss after 13001 iterations 0.44815896487422824
current loss after 14001 iterations 0.4482927277352543
current loss after 15001 iterations 0.44840840556985195
current loss after 16001 iterations 0.44850943004153504
current loss after 17001 iterations 0.4485984168493203
current loss a

In [ ]:
W

array([[ 7.5914125 ],
       [ 0.28992149],
       [-0.62015354],
       [-0.49303807],
       [ 0.23517968],
       [ 0.58212269]])

In [ ]:
ycap = prediction(X, W)
ycap

array([[0.99972657],
       [0.99954899],
       [0.99942636],
       [0.99943003],
       [0.99954042],
       [0.9993182 ],
       [0.9994313 ],
       [0.99960356],
       [0.99956302],
       [0.99948275],
       [0.9995087 ],
       [0.99955247],
       [0.99938064],
       [0.99938022],
       [0.99944429],
       [0.99943547],
       [0.99955888],
       [0.99956581],
       [0.99952799],
       [0.99925958]])

In [ ]:
ycaps=np.where(ycap>0.5,1,0)
ycaps

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
np.c_[Y,ycaps]

array([[1, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 1]])

In [ ]:
def accuarcy(y,ycaps):
  pcnt=np.where(y==ycaps)[0].size
  n=y.shape[0]
  return pcnt/n* 100


In [ ]:
acc=accuarcy(Y,ycaps)
acc

55.00000000000001

In [ ]:
np.where(Y==ycaps)[0].size

11

In [ ]:
#statistical measurement
from numpy.linalg import inv
Ws = inv(X.T.dot(X)).dot(X.T.dot(Y))
Ws

array([[ 0.55      ],
       [ 0.39012509],
       [-0.51713828],
       [ 0.09180071],
       [-0.17229651],
       [ 0.63587867]])

In [ ]:
yc=prediction(X,Ws)
yc

array([[0.69030505],
       [0.70518259],
       [0.55637437],
       [0.76131559],
       [0.72528581],
       [0.41781363],
       [0.50544932],
       [0.69263919],
       [0.52591128],
       [0.73451843],
       [0.57252657],
       [0.68156439],
       [0.4518325 ],
       [0.68992813],
       [0.54020375],
       [0.77279287],
       [0.55406627],
       [0.73694948],
       [0.54875118],
       [0.70210433]])

In [ ]:
ycs=np.where(yc>0.5,1,0)
ycs

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
 accuarcy(Y,ycs)

65.0

In [ ]:
# part2
# improve accuracy with GDA.
# lets Rebuilding.
np.random.seed(101)
W = np.random.random((X.shape[1], Y.shape[1])) * 2 -1
W

array([[ 0.03279726],
       [ 0.14133517],
       [-0.94305155],
       [-0.65695669],
       [ 0.37055396],
       [ 0.66779373]])

In [ ]:
ploss =0
flag =0
conv = 0.0000001
for i in range(100000):
    ycap = prediction(X, W)
    e = Y - ycap
    closs = mse(Y , ycap)
    if i%1000 == 0:
        print(f"current loss after {i+1} iterations {closs}")

    delta =  e * derivative(ycap)   # here is change when comepared with previous training loop.
    W += X.T.dot(delta) * 0.02
    if np.abs(ploss-closs) <= conv:
        print(f"Training Completed after {i+1} iterations ")
        flag=1
        break
    ploss = closs
if flag==0:
   print("Training not Completed run few more iterations ")

current loss after 1 iterations 0.33397923935978474
current loss after 1001 iterations 0.008442384426319774
current loss after 2001 iterations 0.005378622053047968
current loss after 3001 iterations 0.003945487883641593
current loss after 4001 iterations 0.003104105265436848
current loss after 5001 iterations 0.0025505061944426518
current loss after 6001 iterations 0.0021592624508714477
current loss after 7001 iterations 0.001868629181681002
current loss after 8001 iterations 0.0016445937301603636
current loss after 9001 iterations 0.001466870305638434
current loss after 10001 iterations 0.00132261513431793
current loss after 11001 iterations 0.0012033063399156574
Training Completed after 11506 iterations 


In [ ]:
ycap = prediction(X , W)
yc = np.where(ycap>0.5, 1, 0)
acc =accuarcy(Y, yc)
acc

100.0

In [ ]:
np.c_[Y,yc]

array([[1, 1],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1]])

In [ ]:
#Note:
#for regression:
# Loss  --> MSE
# performance  --> R-Square
# for classfication.
# Loss --> CrossEntropy
# performance ---> Confusion Matrix.

In [ ]:
# logistic with GDA part 3.
# Cross Entropy.
# multi class classfication.

In [ ]:
y = [1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0]
len(y)

11

In [ ]:
ycap = [0.9, 0.2, 0.8, 0.1, 0.15, 0.92, 0.89 , 0.1,0.6, 0.8, 0.3]
len(ycap)

11

In [ ]:
import numpy as np
y=np.array(y)
ycap=np.array(ycap)
left=y*np.log(ycap)
rgt=(1-y)*np.log(1-ycap)
lrsum=left+rgt


In [ ]:
left

array([-0.10536052, -0.        , -0.22314355, -0.        , -0.        ,
       -0.08338161, -0.11653382, -0.        , -0.51082562, -0.22314355,
       -0.        ])

In [ ]:
rgt

array([-0.        , -0.22314355, -0.        , -0.10536052, -0.16251893,
       -0.        , -0.        , -0.10536052, -0.        , -0.        ,
       -0.35667494])

In [ ]:
lrsum

array([-0.10536052, -0.22314355, -0.22314355, -0.10536052, -0.16251893,
       -0.08338161, -0.11653382, -0.10536052, -0.51082562, -0.22314355,
       -0.35667494])

In [ ]:
s=lrsum.sum()
ce=-s/len(y)
ce

np.float64(0.20140428393760076)

In [ ]:
def crossentropy(y,ycap):
  y=np.array(y)
  ycap=np.array(ycap)
  left=y*np.log(ycap)
  rgt=(1-y)*np.log(1-ycap)
  lrsum=left+rgt
  s=lrsum.sum()
  ce=-s/len(y)
  return ce

In [ ]:
crossentropy(y,ycap)

np.float64(0.20140428393760076)

In [ ]:
# lets Rebuild our model with crossEntropy instead of taking mse as loss function .

In [ ]:
X

array([[ 1.        , -0.11632626, -0.62884247, -0.42953131,  0.08787149,
         0.04136063],
       [ 1.        ,  0.46530506,  0.4350602 ,  0.8526517 ,  1.02935178,
         0.73070439],
       [ 1.        , -0.93061011, -1.31277989, -1.07062281, -1.79508907,
        -1.33732691],
       [ 1.        ,  1.6285677 ,  1.61295243,  1.4937432 ,  1.34317854,
         1.42004816],
       [ 1.        ,  1.04693638,  1.0810011 ,  0.5962151 ,  0.71552502,
         1.0064419 ],
       [ 1.        , -1.6285677 , -1.61675208, -1.71171431, -2.10891584,
        -2.02667068],
       [ 1.        , -0.46530506, -0.17288418, -0.68596791, -0.22595527,
        -0.64798314],
       [ 1.        ,  0.23265253,  0.13108801,  0.2115602 ,  0.40169825,
         0.45496689],
       [ 1.        , -1.27958891, -1.08480075, -1.32705941, -1.16743555,
        -0.92372065],
       [ 1.        ,  1.39591517,  1.34697676,  1.1090883 ,  1.21764783,
         1.14431065],
       [ 1.        , -0.58163132, -0.43885985, -0.

In [ ]:
scaletest(X)

[np.float64(0.0),
 np.float64(1.0000000000000002),
 np.float64(1.0000000000000002),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0)]

In [ ]:
Y

array([[1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1]])

In [ ]:
#random weightss
np.random.seed(101)
W=np.random.random((X.shape[1],Y.shape[1]))*2-1
W

array([[ 0.03279726],
       [ 0.14133517],
       [-0.94305155],
       [-0.65695669],
       [ 0.37055396],
       [ 0.66779373]])

In [ ]:
ploss=0
flag=0
convg= 0.000001
for i in range(100000):
  ycap=prediction(X,W)
  e=Y-ycap
  closs=crossentropy(Y,ycap)
  if (i%1000)==0:
    print(f"current loss after {i+1} iterations {closs}")
  delta=e*derivative(ycap)
  w+=X.T.dot(delta)*0.02
  if np.abs(ploss-closs)<=convg:
    print(f"Training completed after {i+1} iterations ")
    flag=1
    break
  ploss=closs

if (flag==0):
  print(f"Training not completed need few more iterations")

current loss after 1 iterations 0.8674221471331418
Training completed after 2 iterations 


In [ ]:
ycap=prediction(X,W)
yc=np.where(ycap>0.5,1,0)
acc=accuarcy(Y,yc)
acc

20.0

In [ ]:
np.c_[Y,yc]

array([[1, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 1],
       [1, 0]])

In [ ]:
df = pd.read_csv('/content/diabetics _multi_class.txt')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Age              20 non-null     int64  
 1   BMI              20 non-null     float64
 2   Blood Pressure   20 non-null     int64  
 3   Glucose Level    20 non-null     int64  
 4   Insulin Level    20 non-null     int64  
 5   Diabetic Status  20 non-null     object 
dtypes: float64(1), int64(4), object(1)
memory usage: 1.1+ KB


In [ ]:
inputdf = df.iloc[:, :-1]
inputs = inputdf.to_numpy()

In [ ]:
inputs.shape

(20, 5)

In [ ]:
outputdf=df.iloc[:,-1]
out=outputdf.to_numpy()
slabels=list(set(out))
slabels


['High', 'Low', 'Normal']

In [ ]:
out

array(['Low', 'Normal', 'Low', 'Low', 'Normal', 'High', 'Low', 'Low',
       'Normal', 'Low', 'High', 'Low', 'High', 'Low', 'Normal', 'Low',
       'Low', 'Normal', 'Low', 'High'], dtype=object)

In [ ]:
dinfo={}
for i in range(len(slabels)):
  dinfo[slabels[i]]=i
dinfo

{'High': 0, 'Low': 1, 'Normal': 2}

In [ ]:
nlabels=[dinfo[v] for v in out]
nlabels

[1, 2, 1, 1, 2, 0, 1, 1, 2, 1, 0, 1, 0, 1, 2, 1, 1, 2, 1, 0]

In [ ]:
np.c_[out,nlabels]

array([['Low', 1],
       ['Normal', 2],
       ['Low', 1],
       ['Low', 1],
       ['Normal', 2],
       ['High', 0],
       ['Low', 1],
       ['Low', 1],
       ['Normal', 2],
       ['Low', 1],
       ['High', 0],
       ['Low', 1],
       ['High', 0],
       ['Low', 1],
       ['Normal', 2],
       ['Low', 1],
       ['Low', 1],
       ['Normal', 2],
       ['Low', 1],
       ['High', 0]], dtype=object)

In [ ]:
# one hot transformation --> convert numerical labels into binary array.
#       0 1 2
#----------------
# 0 --> 1 0 0
# 1 --> 0 1 0
# 2 --> 0 0 1
def toBinary(nlabels):
   arr = []
   for  i in nlabels:
       barr = np.zeros(3)
       barr[i] = 1
       arr.append(barr)
   return np.array(arr)

In [ ]:
Y = toBinary(nlabels)
Y.shape

(20, 3)

In [ ]:
Y

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
scaled_inputs=scalematrix(inputs)
scaletest(scaled_inputs)

[np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.float64(0.9999999999999999),
 np.float64(0.9999999999999998)]

In [ ]:
scaled_inputs

array([[-0.05166734, -0.56726298, -0.83650301, -0.53079861, -0.52835517],
       [ 0.46500607,  0.80792001,  0.08780971,  0.10871779,  0.27218297],
       [-1.08501417, -1.161092  , -1.29865937, -1.17031501, -1.32889332],
       [-0.36167139, -0.72353378, -0.37434665, -0.78660517, -0.04803229],
       [ 1.18834885,  0.15158267,  1.01212243,  0.74823419,  0.59239823],
       [ 1.60168758,  1.87056141,  1.93643515,  2.02726699,  1.87325925],
       [-1.80835694, -1.59865023, -1.76081573, -1.80983142, -1.64910857],
       [-1.60168758, -1.22360032, -1.02136555, -1.42612158, -1.00867806],
       [-0.67167544,  0.37036178,  0.54996607, -0.27499205,  0.11207534],
       [ 0.15500202, -0.0984506 , -0.09705284,  0.23662107, -0.36824755],
       [ 1.4983529 ,  1.05795328,  1.47427879,  1.38775059,  1.07272111],
       [-1.29168353, -0.6297713 , -0.65164047, -0.91450845, -0.6884628 ],
       [ 0.98167948,  1.33924071,  0.82725988,  1.00404075,  1.553044  ],
       [-0.15500202,  0.05782019, -0.2

In [ ]:
ones=np.ones(inputs.shape[0])
X=np.c_[ones,scaled_inputs]
X

array([[ 1.        , -0.05166734, -0.56726298, -0.83650301, -0.53079861,
        -0.52835517],
       [ 1.        ,  0.46500607,  0.80792001,  0.08780971,  0.10871779,
         0.27218297],
       [ 1.        , -1.08501417, -1.161092  , -1.29865937, -1.17031501,
        -1.32889332],
       [ 1.        , -0.36167139, -0.72353378, -0.37434665, -0.78660517,
        -0.04803229],
       [ 1.        ,  1.18834885,  0.15158267,  1.01212243,  0.74823419,
         0.59239823],
       [ 1.        ,  1.60168758,  1.87056141,  1.93643515,  2.02726699,
         1.87325925],
       [ 1.        , -1.80835694, -1.59865023, -1.76081573, -1.80983142,
        -1.64910857],
       [ 1.        , -1.60168758, -1.22360032, -1.02136555, -1.42612158,
        -1.00867806],
       [ 1.        , -0.67167544,  0.37036178,  0.54996607, -0.27499205,
         0.11207534],
       [ 1.        ,  0.15500202, -0.0984506 , -0.09705284,  0.23662107,
        -0.36824755],
       [ 1.        ,  1.4983529 ,  1.05795328,  1.

In [ ]:
#randomweights
np.random.seed(101)
w=np.random.random((X.shape[1],Y.shape[1]))*2-1
w.shape

(6, 3)

In [ ]:
w

array([[ 0.03279726,  0.14133517, -0.94305155],
       [-0.65695669,  0.37055396,  0.66779373],
       [-0.38606756,  0.78722616,  0.44308772],
       [-0.62012209,  0.10845518, -0.29573609],
       [-0.63621519,  0.57120352,  0.93096644],
       [-0.53529268, -0.83287713,  0.20709684]])

In [ ]:
ploss=0
flag=0
convg= 0.000001
for i in range(100000):
  ycap=prediction(X,w)
  e=Y-ycap
  closs=crossentropy(Y,ycap)
  if (i%1000)==0:
    print(f"current loss after {i+1} iterations {closs}")
  delta=e*derivative(ycap)
  w+=X.T.dot(delta)*0.02
  if np.abs(ploss-closs)<=convg:
    print(f"Training completed after {i+1} iterations ")
    flag=1
    break
  ploss=closs

if (flag==0):
  print(f"Training not completed need few more iterations")

current loss after 1 iterations 3.712709718382649
current loss after 1001 iterations 0.6364422258375387
current loss after 2001 iterations 0.5855286879959316
current loss after 3001 iterations 0.5711578585334854
Training completed after 3365 iterations 


In [ ]:
w

array([[-4.68265799,  0.28735551, -1.43497109],
       [ 0.29668519, -0.46352431, -0.23440937],
       [ 2.2564064 , -1.91080093, -1.52555201],
       [ 0.41141235, -2.97216281,  2.63047317],
       [ 1.32547587, -0.5813706 , -1.28601331],
       [ 1.30349852, -3.94109477,  0.82239257]])

In [ ]:
ycap=prediction(X,w)
ycap

array([[4.46162364e-04, 9.98115757e-01, 7.51760560e-02],
       [1.00952768e-01, 5.37151087e-02, 7.86025719e-02],
       [1.07329611e-05, 9.99997201e-01, 8.21680847e-02],
       [4.60934384e-04, 9.73318895e-01, 4.35602412e-01],
       [1.40915830e-01, 1.77707311e-03, 5.60336351e-01],
       [9.97371849e-01, 1.07751603e-08, 3.45957251e-01],
       [7.52928271e-07, 9.99999957e-01, 9.68454647e-02],
       [9.69299823e-06, 9.99986434e-01, 2.94205150e-01],
       [1.73205399e-02, 1.16560725e-01, 5.12485933e-01],
       [6.27355302e-03, 8.81406638e-01, 1.01237437e-01],
       [8.80092930e-01, 7.17432189e-06, 3.95421594e-01],
       [1.41288772e-04, 9.99305204e-01, 2.18286666e-01],
       [9.11010039e-01, 6.85953804e-06, 1.75653117e-01],
       [6.62075965e-03, 8.71923200e-01, 8.51056134e-02],
       [4.26910158e-02, 1.12482694e-01, 1.15100925e-01],
       [7.27978280e-04, 9.96979661e-01, 8.53740163e-02],
       [2.17821300e-05, 9.99982854e-01, 1.47599479e-01],
       [1.02126610e-01, 4.18735

In [ ]:
yc=np.where(ycap>0.5,1,0)
yc

array([[0, 1, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 1, 0],
       [1, 0, 0]])

In [ ]:
np.where(Y==yc)[0]

array([ 0,  0,  0,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,
        6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11,
       11, 12, 12, 12, 13, 13, 13, 14, 14, 15, 15, 15, 16, 16, 16, 17, 17,
       18, 18, 18, 19, 19, 19])

In [ ]:
scnt = {}
for idx in np.where(Y == yc)[0]:
   if scnt.get(idx) == None:
        scnt[int(idx)] = 1
   else:
        scnt[int(idx)] += 1

scnt



{0: 3,
 1: 2,
 2: 3,
 3: 3,
 4: 3,
 5: 3,
 6: 3,
 7: 3,
 8: 3,
 9: 3,
 10: 3,
 11: 3,
 12: 3,
 13: 3,
 14: 2,
 15: 3,
 16: 3,
 17: 2,
 18: 3,
 19: 3}

In [ ]:
correctedPredictions = [ k for k in scnt  if scnt[k]==3]
pcnt = len(correctedPredictions)
n = Y.shape[0]
accuracy = pcnt/n * 100
accuracy

85.0