<a href="https://colab.research.google.com/github/rakshithasetty41/machine-learning/blob/main/Tak2_salary_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import joblib

In [9]:
data = {
    "Experience": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Test_Score": [50, 55, 65, 70, 75, 80, 85, 87, 90, 95],
    "Salary": [40000, 45000, 50000, 60000, 65000, 70000, 75000, 80000, 85000, 90000]
}
df=pd.DataFrame(data)
df

Experience  Test_Score  Salary
0           1          50   40000
1           2          55   45000
2           3          65   50000
3           4          70   60000
4           5          75   65000
5           6          80   70000
6           7          85   75000
7           8          87   80000
8           9          90   85000
9          10          95   90000

In [50]:
x_m=df[['Experience','Test_Score']]
y=df['Salary']
x_m.shape

(10, 2)

In [11]:
y.shape

(10,)

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x_m,y,test_size=0.2,random_state=42)

In [52]:
x_train

Experience  Test_Score
5           6          80
0           1          50
7           8          87
2           3          65
9          10          95
4           5          75
3           4          70
6           7          85

In [53]:
x_test

Experience  Test_Score
8           9          90
1           2          55

In [54]:
y_train

5    70000
0    40000
7    80000
2    50000
9    90000
4    65000
3    60000
6    75000
Name: Salary, dtype: int64

In [55]:
y_test

8    85000
1    45000
Name: Salary, dtype: int64

In [56]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(8, 2)
(2, 2)
(8,)
(2,)


In [57]:
model=LinearRegression()
model.fit(x_train,y_train)
y_predict=model.predict(x_test)
y_predict

array([84810.79187106, 45261.03714085])

In [58]:
(y_test.values,np.round(y_predict,2))

(array([85000, 45000]), array([84810.79, 45261.04]))

In [59]:
mse=mean_squared_error(y_test,y_predict)
r2=r2_score(y_test,y_predict)
print("mse:",round(mse,2))
print("r2_score",round(r2,2))

mse: 51970.05
r2_score 1.0


In [60]:
x_s=df[['Experience']]
x_train_s,x_test_s,y_train,y_test=train_test_split(x_s,y,test_size=0.2,random_state=42)

In [61]:
model_s=LinearRegression()
model_s.fit(x_train_s,y_train)
ypred=model_s.predict(x_test_s)
ypred

array([85862.06896552, 46637.93103448])

In [62]:
com=(y_test.values,np.round(ypred,2))
com

(array([85000, 45000]), array([85862.07, 46637.93]))

In [63]:
mse_s=mean_squared_error(y_test,ypred)
r2_S=r2_score(y_test,ypred)
print("mse:",round(mse_s,2))
print("r2_score",round(r2_S,2))

mse: 1712990.49
r2_score 1.0


In [64]:
if r2>=r2_S:
  joblib.dump(model,"best_salary_model.pkl")
else:
  joblib.dump(model_s,"best_Salary_model.pkl")

In [76]:
example = pd.DataFrame([[6, 80]], columns=["Experience", "Test_Score"])
predicted_salary = model.predict(example)
print(predicted_salary)

[69659.54216305]


In [ ]:
#conclusion:The Multiple Linear Regression model accurately predicts salaries using both Experience and Test Score.
#It achieved a lower RMSE and higher R² score compared to the single-feature model, showing better performance.
#Hence, the model_multi is the best model, as it captures more factors affecting salary and provides more reliable predictions.